# Generated by Django 3.2.19 on 2024-01-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
