# Generated by Django 3.2.19 on 2024-01-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_admins_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_ms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя устройства')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name_plural': 'Устройства - Московская 102в/1',
            },
        ),
        migrations.CreateModel(
            name='Note_ms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_from', models.TimeField(verbose_name='Время с')),
                ('time_to', models.TimeField(verbose_name='Время до')),
                ('attendees_count', models.PositiveIntegerField(verbose_name='Количество человек')),
                ('full_name', models.CharField(max_length=255, verbose_name='Фамилия и имя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('devices', models.ManyToManyField(to='main.Device_ms', verbose_name='Устройства')),
            ],
            options={
                'verbose_name_plural': 'Записи Киров - Московская 102в/1',
            },
        ),
    ]
