# Generated by Django 3.2.19 on 2024-01-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20240103_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note_ms',
            name='devices',
        ),
        migrations.AddField(
            model_name='note_ms',
            name='devices',
            field=models.CharField(blank=True, max_length=500, verbose_name='Устройства'),
        ),
    ]
