# Generated by Django 3.2.19 on 2024-01-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20240105_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_ms',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='device_ms',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя устройства'),
        ),
    ]
