# Generated by Django 3.2.19 on 2024-01-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20240105_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='note_ms',
            name='where',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='note_ms',
            name='who',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кем сделана'),
        ),
    ]
