# Generated by Django 3.2.19 on 2024-01-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20240105_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_ms',
            name='attendees_count',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Количество человек'),
        ),
    ]
