# Generated by Django 3.2.19 on 2024-01-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_note_ms_attendees_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_mg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя устройства')),
            ],
            options={
                'verbose_name_plural': 'Устройства - Молодой гвардии 51',
            },
        ),
        migrations.CreateModel(
            name='Note_mg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_from', models.TimeField(verbose_name='Время с')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='Время до')),
                ('devices', models.CharField(blank=True, max_length=500, verbose_name='Устройства')),
                ('attendees_count', models.CharField(blank=True, max_length=60, null=True, verbose_name='Количество человек')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия и имя')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('where', models.CharField(blank=True, max_length=50, null=True, verbose_name='Откуда')),
                ('who', models.CharField(blank=True, max_length=50, null=True, verbose_name='Кем сделана')),
            ],
            options={
                'verbose_name_plural': 'Записи Киров - Молодой гвардии 51',
            },
        ),
    ]
