# Generated by Django 3.2.19 on 2024-01-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_device_mg_note_mg'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClubName', models.CharField(max_length=50, verbose_name='Имя клуба')),
                ('WI', models.CharField(max_length=50, verbose_name='Информация')),
            ],
            options={
                'verbose_name_plural': 'Важная информация',
            },
        ),
    ]
