# Generated by Django 3.2.19 on 2024-01-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_log_mg_log_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_mg',
            name='after',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='log_mg',
            name='before',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='log_ms',
            name='after',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='log_ms',
            name='before',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
