# Generated by Django 3.2.19 on 2024-01-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20240111_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='place_mg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Места - Молодой гвардии 51',
                'verbose_name_plural': 'Места - Молодой гвардии 51',
            },
        ),
        migrations.CreateModel(
            name='place_ms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Места - Московская 102в/1',
                'verbose_name_plural': 'Места - Московская 102в/1',
            },
        ),
    ]
