# Generated by Django 3.2.19 on 2024-01-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_place_mg_place_ms'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhereInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=50, verbose_name='Откуда')),
                ('counter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Статистика - Откуда',
            },
        ),
    ]
