# Generated by Django 3.2.19 on 2024-01-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_whereinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='graph_mg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('Admin_one', models.CharField(max_length=60, null=True)),
                ('Admin_two', models.CharField(max_length=60, null=True)),
                ('Admin_three', models.CharField(max_length=60, null=True)),
                ('Admin_four', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'График смен  - Молодой гвардии 51',
                'verbose_name_plural': 'График смен - Молодой гвардии 51',
            },
        ),
        migrations.CreateModel(
            name='graph_ms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('Admin_one', models.CharField(max_length=60, null=True)),
                ('Admin_two', models.CharField(max_length=60, null=True)),
                ('Admin_three', models.CharField(max_length=60, null=True)),
                ('Admin_four', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'График смен  - Московская 102в/1',
                'verbose_name_plural': 'График смен - Московская 102в/1',
            },
        ),
    ]
