# Generated by Django 3.2.19 on 2024-06-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20240129_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingssite',
            name='keys',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='settingssite',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
