# Generated by Django 3.2.19 on 2024-06-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20240629_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingssite',
            name='keys',
            field=models.TextField(max_length=1000),
        ),
    ]
