# Generated by Django 3.2.19 on 2024-07-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_settingssite_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingssite',
            name='keys',
            field=models.TextField(max_length=4000),
        ),
    ]
