# Generated by Django 3.2.19 on 2024-11-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_settingssite_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games_for_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250, verbose_name='Название')),
                ('Alt_name', models.CharField(max_length=250, verbose_name='Альтернативное название')),
            ],
            options={
                'verbose_name_plural': 'Стек игр',
            },
        ),
    ]
