# Generated by Django 3.2.19 on 2024-11-05 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_games_for_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('club', models.CharField(max_length=250, verbose_name='Клуб')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_places', to='main.games_for_place', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Привязка игры к месту',
                'verbose_name_plural': 'Привязки игр к местам',
            },
        ),
    ]
